-record(ioi, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  ioi_id,
  ioi_trans_type,
  ioi_ref_id,
  side,
  qty_type,
  ioi_qty,
  currency,
  price_type,
  price,
  valid_until_time,
  ioi_qlty_ind,
  ioi_natural_flag,
  text,
  encoded_text,
  transact_time,
  url_link,
  signature,
  underlyings = [],
  legs = [],
  ioi_qualifiers = [],
  routing_ids = [],
  fields = []
}).

-record(advertisement, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  adv_id,
  adv_trans_type,
  adv_ref_id,
  adv_side,
  quantity,
  qty_type,
  price,
  currency,
  trade_date,
  transact_time,
  text,
  encoded_text,
  url_link,
  last_mkt,
  trading_session_id,
  trading_session_sub_id,
  signature,
  legs = [],
  underlyings = [],
  fields = []
}).

-record(execution_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  secondary_exec_id,
  cl_ord_id,
  orig_cl_ord_id,
  cl_ord_link_id,
  quote_resp_id,
  ord_status_req_id,
  mass_status_req_id,
  tot_num_reports,
  last_rpt_requested,
  trade_origination_date,
  list_id,
  cross_id,
  orig_cross_id,
  cross_type,
  exec_id,
  exec_ref_id,
  exec_type,
  ord_status,
  working_indicator,
  ord_rej_reason,
  exec_restatement_reason,
  account,
  acct_id_source,
  account_type,
  day_booking_inst,
  booking_unit,
  prealloc_method,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  side,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  pegged_price,
  discretion_price,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  target_strategy_performance,
  currency,
  compliance_id,
  solicited_flag,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  exec_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  last_qty,
  underlying_last_qty,
  last_px,
  underlying_last_px,
  last_par_px,
  last_spot_rate,
  last_forward_points,
  last_mkt,
  trading_session_id,
  trading_session_sub_id,
  time_bracket,
  last_capacity,
  leaves_qty,
  cum_qty,
  avg_px,
  day_order_qty,
  day_cum_qty,
  day_avg_px,
  gt_booking_inst,
  trade_date,
  transact_time,
  report_to_exch,
  gross_trade_amt,
  num_days_interest,
  ex_date,
  accrued_interest_rate,
  accrued_interest_amt,
  interest_at_maturity,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  traded_flat_switch,
  basis_feature_date,
  basis_feature_price,
  concession,
  total_takedown,
  net_money,
  settl_curr_amt,
  settl_currency,
  settl_curr_fx_rate,
  settl_curr_fx_rate_calc,
  handl_inst,
  min_qty,
  max_floor,
  position_effect,
  max_show,
  booking_type,
  text,
  encoded_text,
  settl_date2,
  order_qty2,
  last_forward_points2,
  multi_leg_reporting_type,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  trans_bkd_time,
  exec_valuation_point,
  exec_price_type,
  exec_price_adjustment,
  priority_indicator,
  price_improvement,
  last_liquidity_ind,
  copy_msg_indicator,
  signature,
  contra_brokers = [],
  underlyings = [],
  cont_amts = [],
  legs = [],
  misc_fees = [],
  fields = []
}).

-record(order_cancel_reject, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  cl_ord_id,
  cl_ord_link_id,
  orig_cl_ord_id,
  ord_status,
  working_indicator,
  orig_ord_mod_time,
  list_id,
  account,
  acct_id_source,
  account_type,
  trade_origination_date,
  trade_date,
  transact_time,
  cxl_rej_response_to,
  cxl_rej_reason,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(news, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  orig_time,
  urgency,
  headline,
  encoded_headline,
  url_link,
  raw_data,
  signature,
  routing_ids = [],
  related_sym = [],
  legs = [],
  underlyings = [],
  lines_of_text = [],
  fields = []
}).

-record(email, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  email_thread_id,
  email_type,
  orig_time,
  subject,
  encoded_subject,
  order_id,
  cl_ord_id,
  raw_data,
  signature,
  routing_ids = [],
  related_sym = [],
  underlyings = [],
  legs = [],
  lines_of_text = [],
  fields = []
}).

-record(new_order_single, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  trade_origination_date,
  trade_date,
  account,
  acct_id_source,
  account_type,
  day_booking_inst,
  booking_unit,
  prealloc_method,
  alloc_id,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  prev_close_px,
  side,
  locate_reqd,
  transact_time,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  solicited_flag,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  settl_date2,
  order_qty2,
  price2,
  position_effect,
  covered_or_uncovered,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  signature,
  allocs = [],
  trading_sessions = [],
  underlyings = [],
  fields = []
}).

-record(new_order_list, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  bid_id,
  client_bid_id,
  prog_rpt_reqs,
  bid_type,
  prog_period_interval,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  list_exec_inst_type,
  list_exec_inst,
  encoded_list_exec_inst,
  allowable_one_sidedness_pct,
  allowable_one_sidedness_value,
  allowable_one_sidedness_curr,
  tot_no_orders,
  last_fragment,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  prev_close_px,
  side,
  side_value_ind,
  locate_reqd,
  transact_time,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  solicited_flag,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  settl_date2,
  order_qty2,
  price2,
  position_effect,
  covered_or_uncovered,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  designation,
  signature,
  orders = [],
  trading_sessions = [],
  underlyings = [],
  fields = []
}).

-record(order_cancel_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  orig_cl_ord_id,
  order_id,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  list_id,
  orig_ord_mod_time,
  account,
  acct_id_source,
  account_type,
  side,
  transact_time,
  compliance_id,
  text,
  encoded_text,
  signature,
  underlyings = [],
  fields = []
}).

-record(order_cancel_replace_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  trade_origination_date,
  trade_date,
  orig_cl_ord_id,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  list_id,
  orig_ord_mod_time,
  account,
  acct_id_source,
  account_type,
  day_booking_inst,
  booking_unit,
  prealloc_method,
  alloc_id,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  side,
  transact_time,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  compliance_id,
  solicited_flag,
  currency,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  settl_date2,
  order_qty2,
  price2,
  position_effect,
  covered_or_uncovered,
  max_show,
  locate_reqd,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  signature,
  allocs = [],
  trading_sessions = [],
  underlyings = [],
  fields = []
}).

-record(order_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  ord_status_req_id,
  account,
  acct_id_source,
  side,
  signature,
  underlyings = [],
  fields = []
}).

-record(allocation_instruction, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  alloc_id,
  alloc_trans_type,
  alloc_type,
  secondary_alloc_id,
  ref_alloc_id,
  alloc_canc_replace_reason,
  alloc_intermed_req_type,
  alloc_link_id,
  alloc_link_type,
  booking_ref_id,
  alloc_no_orders_type,
  previously_reported,
  reversal_indicator,
  match_type,
  side,
  quantity,
  qty_type,
  last_mkt,
  trade_origination_date,
  trading_session_id,
  trading_session_sub_id,
  price_type,
  avg_px,
  avg_par_px,
  currency,
  avg_px_precision,
  trade_date,
  transact_time,
  settl_type,
  settl_date,
  booking_type,
  gross_trade_amt,
  concession,
  total_takedown,
  net_money,
  position_effect,
  auto_accept_indicator,
  text,
  encoded_text,
  num_days_interest,
  accrued_interest_rate,
  accrued_interest_amt,
  total_accrued_interest_amt,
  interest_at_maturity,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  legal_confirm,
  tot_no_allocs,
  last_fragment,
  clearing_fee_indicator,
  alloc_settl_inst_type,
  signature,
  orders = [],
  execs = [],
  underlyings = [],
  legs = [],
  allocs = [],
  clearing_instructions = [],
  fields = []
}).

-record(list_cancel_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  transact_time,
  trade_origination_date,
  trade_date,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(list_execute, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  client_bid_id,
  bid_id,
  transact_time,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(list_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(list_status, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  list_status_type,
  no_rpts,
  list_order_status,
  rpt_seq,
  list_status_text,
  encoded_list_status_text,
  transact_time,
  tot_no_orders,
  last_fragment,
  signature,
  orders = [],
  fields = []
}).

-record(allocation_instruction_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  alloc_id,
  secondary_alloc_id,
  trade_date,
  transact_time,
  alloc_status,
  alloc_rej_code,
  alloc_type,
  alloc_intermed_req_type,
  match_status,
  product,
  security_type,
  text,
  encoded_text,
  signature,
  allocs = [],
  fields = []
}).

-record(dont_know_trade, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  secondary_order_id,
  exec_id,
  dk_reason,
  side,
  last_qty,
  last_px,
  text,
  encoded_text,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(quote_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  rfq_req_id,
  cl_ord_id,
  order_capacity,
  prev_close_px,
  quote_request_type,
  quote_type,
  trading_session_id,
  trading_session_sub_id,
  trade_origination_date,
  side,
  qty_type,
  settl_type,
  settl_date,
  settl_date2,
  order_qty2,
  currency,
  account,
  acct_id_source,
  account_type,
  quote_price_type,
  ord_type,
  valid_until_time,
  expire_time,
  transact_time,
  price_type,
  price,
  price2,
  text,
  encoded_text,
  signature,
  related_sym = [],
  legs = [],
  quote_qualifiers = [],
  fields = []
}).

-record(quote, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  quote_id,
  quote_resp_id,
  quote_type,
  quote_response_level,
  trading_session_id,
  trading_session_sub_id,
  side,
  settl_type,
  settl_date,
  settl_date2,
  order_qty2,
  currency,
  account,
  acct_id_source,
  account_type,
  bid_px,
  offer_px,
  mkt_bid_px,
  mkt_offer_px,
  min_bid_size,
  bid_size,
  min_offer_size,
  offer_size,
  valid_until_time,
  bid_spot_rate,
  offer_spot_rate,
  bid_forward_points,
  offer_forward_points,
  mid_px,
  bid_yield,
  mid_yield,
  offer_yield,
  transact_time,
  ord_type,
  bid_forward_points2,
  offer_forward_points2,
  settl_curr_bid_fx_rate,
  settl_curr_offer_fx_rate,
  settl_curr_fx_rate_calc,
  comm_type,
  commission,
  cust_order_capacity,
  ex_destination,
  order_capacity,
  price_type,
  text,
  encoded_text,
  signature,
  quote_qualifiers = [],
  underlyings = [],
  legs = [],
  fields = []
}).

-record(settlement_instructions, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  settl_inst_msg_id,
  settl_inst_req_id,
  settl_inst_mode,
  settl_inst_req_rej_code,
  text,
  encoded_text,
  cl_ord_id,
  transact_time,
  signature,
  settl_inst = [],
  fields = []
}).

-record(market_data_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  md_req_id,
  subscription_request_type,
  market_depth,
  md_update_type,
  aggregated_book,
  open_close_settl_flag,
  scope,
  md_implicit_delete,
  appl_queue_action,
  appl_queue_max,
  signature,
  md_entry_types = [],
  related_sym = [],
  legs = [],
  trading_sessions = [],
  fields = []
}).

-record(market_data_snapshot_full_refresh, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  md_req_id,
  financial_status,
  corporate_action,
  net_chg_prev_day,
  appl_queue_depth,
  appl_queue_resolution,
  signature,
  underlyings = [],
  legs = [],
  md_entries = [],
  fields = []
}).

-record(market_data_incremental_refresh, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  md_req_id,
  financial_status,
  corporate_action,
  md_entry_px,
  currency,
  md_entry_size,
  md_entry_date,
  md_entry_time,
  tick_direction,
  md_mkt,
  trading_session_id,
  trading_session_sub_id,
  quote_condition,
  trade_condition,
  md_entry_originator,
  location_id,
  desk_id,
  open_close_settl_flag,
  time_in_force,
  expire_date,
  expire_time,
  min_qty,
  exec_inst,
  seller_days,
  order_id,
  quote_entry_id,
  md_entry_buyer,
  md_entry_seller,
  number_of_orders,
  md_entry_position_no,
  scope,
  price_delta,
  net_chg_prev_day,
  text,
  encoded_text,
  appl_queue_depth,
  appl_queue_resolution,
  signature,
  md_entries = [],
  legs = [],
  fields = []
}).

-record(market_data_request_reject, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  md_req_id,
  md_req_rej_reason,
  text,
  encoded_text,
  signature,
  alt_md_source = [],
  fields = []
}).

-record(quote_cancel, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  quote_id,
  quote_cancel_type,
  quote_response_level,
  account,
  acct_id_source,
  account_type,
  trading_session_id,
  trading_session_sub_id,
  signature,
  quote_entries = [],
  legs = [],
  fields = []
}).

-record(quote_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_status_req_id,
  quote_id,
  account,
  acct_id_source,
  account_type,
  trading_session_id,
  trading_session_sub_id,
  subscription_request_type,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(mass_quote_acknowledgement, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  quote_id,
  quote_status,
  quote_reject_reason,
  quote_response_level,
  quote_type,
  account,
  acct_id_source,
  account_type,
  text,
  encoded_text,
  bid_px,
  offer_px,
  bid_size,
  offer_size,
  valid_until_time,
  bid_spot_rate,
  offer_spot_rate,
  bid_forward_points,
  offer_forward_points,
  mid_px,
  bid_yield,
  mid_yield,
  offer_yield,
  transact_time,
  trading_session_id,
  trading_session_sub_id,
  settl_date,
  ord_type,
  settl_date2,
  order_qty2,
  bid_forward_points2,
  offer_forward_points2,
  currency,
  quote_entry_reject_reason,
  signature,
  quote_sets = [],
  fields = []
}).

-record(security_definition_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_request_type,
  currency,
  text,
  encoded_text,
  trading_session_id,
  trading_session_sub_id,
  expiration_cycle,
  subscription_request_type,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(security_definition, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_response_id,
  security_response_type,
  currency,
  trading_session_id,
  trading_session_sub_id,
  text,
  encoded_text,
  expiration_cycle,
  round_lot,
  min_trade_vol,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(security_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_status_req_id,
  currency,
  subscription_request_type,
  trading_session_id,
  trading_session_sub_id,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(security_status, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_status_req_id,
  currency,
  trading_session_id,
  trading_session_sub_id,
  unsolicited_indicator,
  security_trading_status,
  financial_status,
  corporate_action,
  halt_reason_char,
  in_view_of_common,
  due_to_related,
  buy_volume,
  sell_volume,
  high_px,
  low_px,
  last_px,
  transact_time,
  adjustment,
  text,
  encoded_text,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(trading_session_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trad_ses_req_id,
  trading_session_id,
  trading_session_sub_id,
  trad_ses_method,
  trad_ses_mode,
  subscription_request_type,
  signature,
  fields = []
}).

-record(trading_session_status, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trad_ses_req_id,
  trading_session_id,
  trading_session_sub_id,
  trad_ses_method,
  trad_ses_mode,
  unsolicited_indicator,
  trad_ses_status,
  trad_ses_status_rej_reason,
  trad_ses_start_time,
  trad_ses_open_time,
  trad_ses_pre_close_time,
  trad_ses_close_time,
  trad_ses_end_time,
  total_volume_traded,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(mass_quote, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  quote_id,
  quote_type,
  quote_response_level,
  account,
  acct_id_source,
  account_type,
  def_bid_size,
  def_offer_size,
  bid_px,
  offer_px,
  bid_size,
  offer_size,
  valid_until_time,
  bid_spot_rate,
  offer_spot_rate,
  bid_forward_points,
  offer_forward_points,
  mid_px,
  bid_yield,
  mid_yield,
  offer_yield,
  transact_time,
  trading_session_id,
  trading_session_sub_id,
  settl_date,
  ord_type,
  settl_date2,
  order_qty2,
  bid_forward_points2,
  offer_forward_points2,
  currency,
  signature,
  quote_sets = [],
  fields = []
}).

-record(business_message_reject, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  ref_seq_num,
  ref_msg_type,
  business_reject_ref_id,
  business_reject_reason,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(bid_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  bid_id,
  client_bid_id,
  bid_request_trans_type,
  list_name,
  tot_no_related_sym,
  bid_type,
  num_tickets,
  currency,
  side_value1,
  side_value2,
  liquidity_ind_type,
  wt_average_liquidity,
  exchange_for_physical,
  out_main_cntry_u_index,
  cross_percent,
  prog_rpt_reqs,
  prog_period_interval,
  inc_tax_ind,
  forex_req,
  num_bidders,
  trade_date,
  bid_trade_type,
  basis_px_type,
  strike_time,
  text,
  encoded_text,
  signature,
  bid_descriptors = [],
  bid_components = [],
  fields = []
}).

-record(bid_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  bid_id,
  client_bid_id,
  signature,
  bid_components = [],
  fields = []
}).

-record(list_strike_price, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  list_id,
  tot_no_strikes,
  last_fragment,
  signature,
  strikes = [],
  underlyings = [],
  fields = []
}).

-record(registration_instructions, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  regist_id,
  regist_trans_type,
  regist_ref_id,
  cl_ord_id,
  account,
  acct_id_source,
  regist_acct_type,
  tax_advantage_type,
  ownership_type,
  signature,
  regist_dtls = [],
  distrib_insts = [],
  fields = []
}).

-record(registration_instructions_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  regist_id,
  regist_trans_type,
  regist_ref_id,
  cl_ord_id,
  account,
  acct_id_source,
  regist_status,
  regist_rej_reason_code,
  regist_rej_reason_text,
  signature,
  fields = []
}).

-record(order_mass_cancel_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  cl_ord_id,
  secondary_cl_ord_id,
  mass_cancel_request_type,
  trading_session_id,
  trading_session_sub_id,
  side,
  transact_time,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(order_mass_cancel_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  cl_ord_id,
  secondary_cl_ord_id,
  order_id,
  secondary_order_id,
  mass_cancel_request_type,
  mass_cancel_response,
  mass_cancel_reject_reason,
  total_affected_orders,
  trading_session_id,
  trading_session_sub_id,
  side,
  transact_time,
  text,
  encoded_text,
  signature,
  affected_orders = [],
  fields = []
}).

-record(new_order_cross, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  cross_id,
  cross_type,
  cross_prioritization,
  qty_type,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  position_effect,
  covered_or_uncovered,
  cash_margin,
  clearing_fee_indicator,
  solicited_flag,
  side_compliance_id,
  settl_type,
  settl_date,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  prev_close_px,
  locate_reqd,
  transact_time,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  signature,
  sides = [],
  underlyings = [],
  legs = [],
  trading_sessions = [],
  fields = []
}).

-record(cross_order_cancel_replace_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  cross_id,
  orig_cross_id,
  cross_type,
  cross_prioritization,
  qty_type,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  position_effect,
  covered_or_uncovered,
  cash_margin,
  clearing_fee_indicator,
  solicited_flag,
  side_compliance_id,
  settl_type,
  settl_date,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  prev_close_px,
  locate_reqd,
  transact_time,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  signature,
  sides = [],
  underlyings = [],
  legs = [],
  trading_sessions = [],
  fields = []
}).

-record(cross_order_cancel_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  cross_id,
  orig_cross_id,
  cross_type,
  cross_prioritization,
  transact_time,
  signature,
  sides = [],
  underlyings = [],
  legs = [],
  fields = []
}).

-record(security_type_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  text,
  encoded_text,
  trading_session_id,
  trading_session_sub_id,
  product,
  security_type,
  security_sub_type,
  signature,
  fields = []
}).

-record(security_types, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_response_id,
  security_response_type,
  tot_no_security_types,
  last_fragment,
  text,
  encoded_text,
  trading_session_id,
  trading_session_sub_id,
  subscription_request_type,
  signature,
  security_types = [],
  fields = []
}).

-record(security_list_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_list_request_type,
  currency,
  text,
  encoded_text,
  trading_session_id,
  trading_session_sub_id,
  subscription_request_type,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(security_list, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_response_id,
  security_request_result,
  tot_no_related_sym,
  last_fragment,
  currency,
  round_lot,
  min_trade_vol,
  trading_session_id,
  trading_session_sub_id,
  expiration_cycle,
  text,
  encoded_text,
  signature,
  related_sym = [],
  legs = [],
  fields = []
}).

-record(derivative_security_list_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_list_request_type,
  security_sub_type,
  currency,
  text,
  encoded_text,
  trading_session_id,
  trading_session_sub_id,
  subscription_request_type,
  signature,
  fields = []
}).

-record(derivative_security_list, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  security_req_id,
  security_response_id,
  security_request_result,
  tot_no_related_sym,
  last_fragment,
  trading_session_id,
  trading_session_sub_id,
  text,
  encoded_text,
  signature,
  related_sym = [],
  fields = []
}).

-record(new_order_multileg, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  trade_origination_date,
  trade_date,
  account,
  acct_id_source,
  account_type,
  day_booking_inst,
  booking_unit,
  prealloc_method,
  alloc_id,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  side,
  prev_close_px,
  leg_position_effect,
  leg_covered_or_uncovered,
  leg_ref_id,
  leg_price,
  leg_settl_type,
  leg_settl_date,
  locate_reqd,
  transact_time,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  solicited_flag,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  position_effect,
  covered_or_uncovered,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  multi_leg_rpt_type_req,
  signature,
  allocs = [],
  trading_sessions = [],
  underlyings = [],
  legs = [],
  fields = []
}).

-record(multileg_order_cancel_replace, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  order_id,
  orig_cl_ord_id,
  cl_ord_id,
  secondary_cl_ord_id,
  cl_ord_link_id,
  orig_ord_mod_time,
  trade_origination_date,
  trade_date,
  account,
  acct_id_source,
  account_type,
  day_booking_inst,
  booking_unit,
  prealloc_method,
  alloc_id,
  settl_type,
  settl_date,
  cash_margin,
  clearing_fee_indicator,
  handl_inst,
  exec_inst,
  min_qty,
  max_floor,
  ex_destination,
  process_code,
  side,
  prev_close_px,
  leg_position_effect,
  leg_covered_or_uncovered,
  leg_ref_id,
  leg_price,
  leg_settl_type,
  leg_settl_date,
  locate_reqd,
  transact_time,
  qty_type,
  ord_type,
  price_type,
  price,
  stop_px,
  currency,
  compliance_id,
  solicited_flag,
  ioi_id,
  quote_id,
  time_in_force,
  effective_time,
  expire_date,
  expire_time,
  gt_booking_inst,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  forex_req,
  settl_currency,
  booking_type,
  text,
  encoded_text,
  position_effect,
  covered_or_uncovered,
  max_show,
  target_strategy,
  target_strategy_parameters,
  participation_rate,
  cancellation_rights,
  money_laundering_status,
  regist_id,
  designation,
  multi_leg_rpt_type_req,
  signature,
  allocs = [],
  trading_sessions = [],
  underlyings = [],
  legs = [],
  fields = []
}).

-record(trade_capture_report_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trade_request_id,
  trade_request_type,
  subscription_request_type,
  trade_report_id,
  secondary_trade_report_id,
  exec_id,
  exec_type,
  order_id,
  cl_ord_id,
  match_status,
  trd_type,
  trd_sub_type,
  transfer_reason,
  secondary_trd_type,
  trade_link_id,
  trd_match_id,
  clearing_business_date,
  trading_session_id,
  trading_session_sub_id,
  time_bracket,
  side,
  multi_leg_reporting_type,
  trade_input_source,
  trade_input_device,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  signature,
  underlyings = [],
  legs = [],
  dates = [],
  fields = []
}).

-record(trade_capture_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trade_report_id,
  trade_report_trans_type,
  trade_report_type,
  trade_request_id,
  trd_type,
  trd_sub_type,
  secondary_trd_type,
  transfer_reason,
  exec_type,
  tot_num_trade_reports,
  last_rpt_requested,
  unsolicited_indicator,
  subscription_request_type,
  trade_report_ref_id,
  secondary_trade_report_ref_id,
  secondary_trade_report_id,
  trade_link_id,
  trd_match_id,
  exec_id,
  ord_status,
  secondary_exec_id,
  exec_restatement_reason,
  previously_reported,
  price_type,
  qty_type,
  underlying_trading_session_id,
  underlying_trading_session_sub_id,
  last_qty,
  last_px,
  last_par_px,
  last_spot_rate,
  last_forward_points,
  last_mkt,
  trade_date,
  clearing_business_date,
  avg_px,
  avg_px_indicator,
  multi_leg_reporting_type,
  trade_leg_ref_id,
  transact_time,
  settl_type,
  settl_date,
  match_status,
  match_type,
  clearing_fee_indicator,
  trade_input_source,
  trade_input_device,
  order_input_device,
  currency,
  compliance_id,
  solicited_flag,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  ord_type,
  exec_inst,
  trans_bkd_time,
  trading_session_id,
  trading_session_sub_id,
  time_bracket,
  gross_trade_amt,
  num_days_interest,
  ex_date,
  accrued_interest_rate,
  accrued_interest_amt,
  interest_at_maturity,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  concession,
  total_takedown,
  net_money,
  settl_curr_amt,
  settl_currency,
  settl_curr_fx_rate,
  settl_curr_fx_rate_calc,
  position_effect,
  text,
  encoded_text,
  side_multi_leg_reporting_type,
  exchange_rule,
  trade_alloc_indicator,
  prealloc_method,
  alloc_id,
  copy_msg_indicator,
  publish_trd_indicator,
  short_sale_reason,
  signature,
  underlyings = [],
  legs = [],
  sides = [],
  cont_amts = [],
  misc_fees = [],
  allocs = [],
  fields = []
}).

-record(order_mass_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  mass_status_req_id,
  mass_status_req_type,
  account,
  acct_id_source,
  trading_session_id,
  trading_session_sub_id,
  side,
  signature,
  fields = []
}).

-record(quote_request_reject, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_req_id,
  rfq_req_id,
  quote_request_reject_reason,
  prev_close_px,
  quote_request_type,
  quote_type,
  trading_session_id,
  trading_session_sub_id,
  trade_origination_date,
  side,
  qty_type,
  settl_type,
  settl_date,
  settl_date2,
  order_qty2,
  currency,
  account,
  acct_id_source,
  account_type,
  quote_price_type,
  ord_type,
  expire_time,
  transact_time,
  price_type,
  price,
  price2,
  text,
  encoded_text,
  signature,
  related_sym = [],
  legs = [],
  quote_qualifiers = [],
  fields = []
}).

-record(rfq_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  rfq_req_id,
  prev_close_px,
  quote_request_type,
  quote_type,
  trading_session_id,
  trading_session_sub_id,
  subscription_request_type,
  signature,
  related_sym = [],
  legs = [],
  fields = []
}).

-record(quote_status_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_status_req_id,
  quote_req_id,
  quote_id,
  quote_resp_id,
  quote_type,
  trading_session_id,
  trading_session_sub_id,
  side,
  settl_type,
  settl_date,
  settl_date2,
  order_qty2,
  currency,
  account,
  acct_id_source,
  account_type,
  expire_time,
  price,
  price_type,
  bid_px,
  offer_px,
  mkt_bid_px,
  mkt_offer_px,
  min_bid_size,
  bid_size,
  min_offer_size,
  offer_size,
  valid_until_time,
  bid_spot_rate,
  offer_spot_rate,
  bid_forward_points,
  offer_forward_points,
  mid_px,
  bid_yield,
  mid_yield,
  offer_yield,
  transact_time,
  ord_type,
  bid_forward_points2,
  offer_forward_points2,
  settl_curr_bid_fx_rate,
  settl_curr_offer_fx_rate,
  settl_curr_fx_rate_calc,
  comm_type,
  commission,
  cust_order_capacity,
  ex_destination,
  quote_status,
  text,
  encoded_text,
  signature,
  underlyings = [],
  legs = [],
  quote_qualifiers = [],
  fields = []
}).

-record(quote_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  quote_resp_id,
  quote_id,
  quote_resp_type,
  cl_ord_id,
  order_capacity,
  ioi_id,
  quote_type,
  trading_session_id,
  trading_session_sub_id,
  side,
  settl_type,
  settl_date,
  settl_date2,
  order_qty2,
  currency,
  account,
  acct_id_source,
  account_type,
  bid_px,
  offer_px,
  mkt_bid_px,
  mkt_offer_px,
  min_bid_size,
  bid_size,
  min_offer_size,
  offer_size,
  valid_until_time,
  bid_spot_rate,
  offer_spot_rate,
  bid_forward_points,
  offer_forward_points,
  mid_px,
  bid_yield,
  mid_yield,
  offer_yield,
  transact_time,
  ord_type,
  bid_forward_points2,
  offer_forward_points2,
  settl_curr_bid_fx_rate,
  settl_curr_offer_fx_rate,
  settl_curr_fx_rate_calc,
  commission,
  comm_type,
  cust_order_capacity,
  ex_destination,
  text,
  encoded_text,
  price,
  price_type,
  signature,
  quote_qualifiers = [],
  underlyings = [],
  legs = [],
  fields = []
}).

-record(confirmation, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  confirm_id,
  confirm_ref_id,
  confirm_req_id,
  confirm_trans_type,
  confirm_type,
  copy_msg_indicator,
  legal_confirm,
  confirm_status,
  alloc_id,
  secondary_alloc_id,
  individual_alloc_id,
  transact_time,
  trade_date,
  alloc_qty,
  qty_type,
  side,
  currency,
  last_mkt,
  alloc_account,
  alloc_acct_id_source,
  alloc_account_type,
  avg_px,
  avg_px_precision,
  price_type,
  avg_par_px,
  reported_px,
  text,
  encoded_text,
  process_code,
  gross_trade_amt,
  num_days_interest,
  ex_date,
  accrued_interest_rate,
  accrued_interest_amt,
  interest_at_maturity,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  concession,
  total_takedown,
  net_money,
  maturity_net_money,
  settl_curr_amt,
  settl_currency,
  settl_curr_fx_rate,
  settl_curr_fx_rate_calc,
  settl_type,
  settl_date,
  shared_commission,
  signature,
  orders = [],
  underlyings = [],
  legs = [],
  capacities = [],
  misc_fees = [],
  fields = []
}).

-record(position_maintenance_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  pos_req_id,
  pos_trans_type,
  pos_maint_action,
  orig_pos_req_ref_id,
  pos_maint_rpt_ref_id,
  clearing_business_date,
  settl_sess_id,
  settl_sess_sub_id,
  account,
  acct_id_source,
  account_type,
  currency,
  transact_time,
  adjustment_type,
  contrary_instruction_indicator,
  prior_spread_indicator,
  threshold_amount,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  trading_sessions = [],
  fields = []
}).

-record(position_maintenance_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  pos_maint_rpt_id,
  pos_trans_type,
  pos_req_id,
  pos_maint_action,
  orig_pos_req_ref_id,
  pos_maint_status,
  pos_maint_result,
  clearing_business_date,
  settl_sess_id,
  settl_sess_sub_id,
  account,
  acct_id_source,
  account_type,
  currency,
  transact_time,
  adjustment_type,
  threshold_amount,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  trading_sessions = [],
  fields = []
}).

-record(request_for_positions, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  pos_req_id,
  pos_req_type,
  match_status,
  subscription_request_type,
  account,
  acct_id_source,
  account_type,
  currency,
  clearing_business_date,
  settl_sess_id,
  settl_sess_sub_id,
  transact_time,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  trading_sessions = [],
  fields = []
}).

-record(request_for_positions_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  pos_maint_rpt_id,
  pos_req_id,
  total_num_pos_reports,
  unsolicited_indicator,
  pos_req_result,
  pos_req_status,
  account,
  acct_id_source,
  account_type,
  currency,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  fields = []
}).

-record(position_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  pos_maint_rpt_id,
  pos_req_id,
  pos_req_type,
  subscription_request_type,
  total_num_pos_reports,
  unsolicited_indicator,
  pos_req_result,
  clearing_business_date,
  settl_sess_id,
  settl_sess_sub_id,
  account,
  acct_id_source,
  account_type,
  currency,
  settl_price,
  settl_price_type,
  prior_settl_price,
  regist_status,
  delivery_date,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  fields = []
}).

-record(trade_capture_report_request_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trade_request_id,
  trade_request_type,
  subscription_request_type,
  tot_num_trade_reports,
  trade_request_result,
  trade_request_status,
  multi_leg_reporting_type,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  signature,
  underlyings = [],
  legs = [],
  fields = []
}).

-record(trade_capture_report_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  trade_report_id,
  trade_report_trans_type,
  trade_report_type,
  trd_type,
  trd_sub_type,
  secondary_trd_type,
  transfer_reason,
  exec_type,
  trade_report_ref_id,
  secondary_trade_report_ref_id,
  trd_rpt_status,
  trade_report_reject_reason,
  secondary_trade_report_id,
  subscription_request_type,
  trade_link_id,
  trd_match_id,
  exec_id,
  secondary_exec_id,
  transact_time,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  clearing_fee_indicator,
  order_capacity,
  order_restrictions,
  cust_order_capacity,
  account,
  acct_id_source,
  account_type,
  position_effect,
  prealloc_method,
  signature,
  legs = [],
  allocs = [],
  fields = []
}).

-record(allocation_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  alloc_report_id,
  alloc_id,
  alloc_trans_type,
  alloc_report_ref_id,
  alloc_canc_replace_reason,
  secondary_alloc_id,
  alloc_report_type,
  alloc_status,
  alloc_rej_code,
  ref_alloc_id,
  alloc_intermed_req_type,
  alloc_link_id,
  alloc_link_type,
  booking_ref_id,
  alloc_no_orders_type,
  previously_reported,
  reversal_indicator,
  match_type,
  side,
  quantity,
  qty_type,
  last_mkt,
  trade_origination_date,
  trading_session_id,
  trading_session_sub_id,
  price_type,
  avg_px,
  avg_par_px,
  currency,
  avg_px_precision,
  trade_date,
  transact_time,
  settl_type,
  settl_date,
  booking_type,
  gross_trade_amt,
  concession,
  total_takedown,
  net_money,
  position_effect,
  auto_accept_indicator,
  text,
  encoded_text,
  num_days_interest,
  accrued_interest_rate,
  accrued_interest_amt,
  total_accrued_interest_amt,
  interest_at_maturity,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  legal_confirm,
  tot_no_allocs,
  last_fragment,
  clearing_fee_indicator,
  alloc_settl_inst_type,
  signature,
  orders = [],
  execs = [],
  underlyings = [],
  legs = [],
  allocs = [],
  clearing_instructions = [],
  fields = []
}).

-record(allocation_report_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  alloc_report_id,
  alloc_id,
  secondary_alloc_id,
  trade_date,
  transact_time,
  alloc_status,
  alloc_rej_code,
  alloc_report_type,
  alloc_intermed_req_type,
  match_status,
  product,
  security_type,
  text,
  encoded_text,
  signature,
  allocs = [],
  fields = []
}).

-record(confirmation_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  confirm_id,
  trade_date,
  transact_time,
  affirm_status,
  confirm_rej_reason,
  match_status,
  text,
  encoded_text,
  signature,
  fields = []
}).

-record(settlement_instruction_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  settl_inst_req_id,
  transact_time,
  alloc_account,
  alloc_acct_id_source,
  side,
  product,
  security_type,
  cfi_code,
  effective_time,
  expire_time,
  last_update_time,
  stand_inst_db_type,
  stand_inst_db_name,
  stand_inst_db_id,
  signature,
  fields = []
}).

-record(assignment_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  asgn_rpt_id,
  tot_num_assignment_reports,
  last_rpt_requested,
  account,
  account_type,
  currency,
  threshold_amount,
  settl_price,
  settl_price_type,
  underlying_settl_price,
  expire_date,
  assignment_method,
  assignment_unit,
  open_interest,
  exercise_method,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  text,
  encoded_text,
  signature,
  legs = [],
  underlyings = [],
  fields = []
}).

-record(collateral_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_req_id,
  coll_asgn_reason,
  transact_time,
  expire_time,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  margin_excess,
  total_net_value,
  cash_outstanding,
  side,
  price,
  price_type,
  accrued_interest_amt,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  trading_session_id,
  trading_session_sub_id,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  text,
  encoded_text,
  signature,
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  misc_fees = [],
  fields = []
}).

-record(collateral_assignment, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_asgn_id,
  coll_req_id,
  coll_asgn_reason,
  coll_asgn_trans_type,
  coll_asgn_ref_id,
  transact_time,
  expire_time,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  margin_excess,
  total_net_value,
  cash_outstanding,
  side,
  price,
  price_type,
  accrued_interest_amt,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  trading_session_id,
  trading_session_sub_id,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  text,
  encoded_text,
  signature,
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  misc_fees = [],
  fields = []
}).

-record(collateral_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_resp_id,
  coll_asgn_id,
  coll_req_id,
  coll_asgn_reason,
  coll_asgn_trans_type,
  coll_asgn_resp_type,
  coll_asgn_reject_reason,
  transact_time,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  margin_excess,
  total_net_value,
  cash_outstanding,
  side,
  price,
  price_type,
  accrued_interest_amt,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  text,
  encoded_text,
  signature,
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  misc_fees = [],
  fields = []
}).

-record(collateral_report, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_rpt_id,
  coll_inquiry_id,
  coll_status,
  tot_num_reports,
  last_rpt_requested,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  margin_excess,
  total_net_value,
  cash_outstanding,
  side,
  price,
  price_type,
  accrued_interest_amt,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  trading_session_id,
  trading_session_sub_id,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  text,
  encoded_text,
  signature,
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  misc_fees = [],
  fields = []
}).

-record(collateral_inquiry, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_inquiry_id,
  subscription_request_type,
  response_transport_type,
  response_destination,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  margin_excess,
  total_net_value,
  cash_outstanding,
  side,
  price,
  price_type,
  accrued_interest_amt,
  end_accrued_interest_amt,
  start_cash,
  end_cash,
  trading_session_id,
  trading_session_sub_id,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  text,
  encoded_text,
  signature,
  coll_inquiry_qualifier = [],
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  fields = []
}).

-record(network_counterparty_system_status_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  network_request_type,
  network_request_id,
  signature,
  comp_ids = [],
  fields = []
}).

-record(network_counterparty_system_status_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  network_status_response_type,
  network_request_id,
  network_response_id,
  last_network_response_id,
  signature,
  comp_ids = [],
  fields = []
}).

-record(user_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  user_request_id,
  user_request_type,
  username,
  password,
  new_password,
  raw_data,
  signature,
  fields = []
}).

-record(user_response, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  user_request_id,
  username,
  user_status,
  user_status_text,
  signature,
  fields = []
}).

-record(collateral_inquiry_ack, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  coll_inquiry_id,
  coll_inquiry_status,
  coll_inquiry_result,
  tot_num_reports,
  account,
  account_type,
  cl_ord_id,
  order_id,
  secondary_order_id,
  secondary_cl_ord_id,
  settl_date,
  quantity,
  qty_type,
  currency,
  trading_session_id,
  trading_session_sub_id,
  settl_sess_id,
  settl_sess_sub_id,
  clearing_business_date,
  response_transport_type,
  response_destination,
  text,
  encoded_text,
  signature,
  coll_inquiry_qualifier = [],
  execs = [],
  trades = [],
  legs = [],
  underlyings = [],
  fields = []
}).

-record(confirmation_request, {
  sender_comp_id,
  target_comp_id,
  msg_seq_num,
  sending_time,
  confirm_req_id,
  confirm_type,
  alloc_id,
  secondary_alloc_id,
  individual_alloc_id,
  transact_time,
  alloc_account,
  alloc_acct_id_source,
  alloc_account_type,
  text,
  encoded_text,
  signature,
  orders = [],
  fields = []
}).

